# Generated by Django 4.1.2 on 2022-10-19 07:20

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Executor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='API_AboutUs',
            fields=[
                ('executor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='front.executor')),
                ('link', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка')),
                ('title', models.CharField(blank=True, max_length=250, verbose_name='Заголовок')),
                ('text', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Текст')),
                ('image', models.ImageField(blank=True, null=True, upload_to='imgAboutUs', verbose_name='Картинка')),
                ('createdat', models.DateTimeField(auto_now=True, db_column='createdAt')),
                ('updatedat', models.DateTimeField(auto_now_add=True, db_column='updatedAt')),
            ],
            options={
                'verbose_name': 'О нас',
                'verbose_name_plural': 'О нас',
                'db_table': 'API_AboutUs',
            },
            bases=('front.executor', models.Model),
        ),
        migrations.CreateModel(
            name='API_Analyses',
            fields=[
                ('executor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='front.executor')),
                ('link', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка')),
                ('title', models.CharField(blank=True, max_length=1000, verbose_name='Короткий заголовок')),
                ('long_title', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Длинный заголовк')),
                ('is_unique', models.BooleanField(blank=True, verbose_name='Уникальный')),
                ('research_id', models.CharField(blank=True, max_length=250, verbose_name='Код анализа')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='Цена')),
                ('preparation_doctor', models.TextField(blank=True, null=True, verbose_name='Инструкция для врача ')),
                ('document_img', models.FileField(blank=True, max_length=1000, null=True, upload_to='imgAnalyse', verbose_name='Файл для документа')),
                ('main_img', models.ImageField(blank=True, max_length=1000, null=True, upload_to='imgAnalyse', verbose_name='Главная картинка')),
                ('description_patient', models.TextField(blank=True, null=True, verbose_name='Описание для пациентов')),
                ('preparation_patient', models.TextField(blank=True, null=True, verbose_name='Инструкция для пациентов')),
                ('description_doctor', models.TextField(blank=True, null=True, verbose_name='Описание для врачей')),
                ('createdat', models.DateTimeField(auto_now=True, db_column='createdAt')),
                ('updatedat', models.DateTimeField(auto_now_add=True, db_column='updatedAt')),
                ('vendor_code', models.CharField(max_length=250, verbose_name='Артикул анализа')),
            ],
            options={
                'verbose_name': 'Анализ',
                'verbose_name_plural': 'Анализы',
                'db_table': 'API_Analyses',
            },
            bases=('front.executor', models.Model),
        ),
        migrations.CreateModel(
            name='API_Biomaterial',
            fields=[
                ('executor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='front.executor')),
                ('title', models.CharField(max_length=250, null=True, verbose_name='Биоматериалы')),
                ('createdat', models.DateTimeField(auto_now=True, db_column='createdAt')),
                ('updatedat', models.DateTimeField(auto_now_add=True, db_column='updatedAt')),
            ],
            options={
                'verbose_name': 'Биоматериал',
                'verbose_name_plural': 'Биоматериалы',
                'db_table': 'API_Biomaterial',
            },
            bases=('front.executor',),
        ),
        migrations.CreateModel(
            name='API_CategoryAnalyses',
            fields=[
                ('executor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='front.executor')),
                ('title', models.CharField(blank=True, max_length=250, null=True, verbose_name='Название категорий')),
                ('createdat', models.DateTimeField(auto_now=True, db_column='createdAt')),
                ('updatedat', models.DateTimeField(auto_now_add=True, db_column='updatedAt')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'db_table': 'API_CategoryAnalyses',
            },
            bases=('front.executor',),
        ),
        migrations.CreateModel(
            name='API_Contacts',
            fields=[
                ('executor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='front.executor')),
                ('link', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка')),
                ('address', models.CharField(blank=True, max_length=100, verbose_name='Адрес')),
                ('phone_number', models.CharField(blank=True, max_length=11, null=True, verbose_name='Номер телефона')),
                ('map', models.CharField(blank=True, max_length=250, null=True, verbose_name='Карта')),
                ('createdat', models.DateTimeField(auto_now=True, db_column='createdAt')),
                ('updatedat', models.DateTimeField(auto_now_add=True, db_column='updatedAt')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
                'db_table': 'API_Contacts',
            },
            bases=('front.executor', models.Model),
        ),
        migrations.CreateModel(
            name='API_News',
            fields=[
                ('executor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='front.executor')),
                ('link', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка')),
                ('img_news', models.ImageField(blank=True, max_length=255, null=True, upload_to='imgNews', verbose_name='Картинка новости')),
                ('title', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Заголовок новости')),
                ('href', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка')),
                ('date', models.CharField(blank=True, max_length=255, null=True, verbose_name='Дата')),
                ('createdat', models.DateTimeField(auto_now=True, db_column='createdAt')),
                ('updatedat', models.DateTimeField(auto_now_add=True, db_column='updatedAt')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'db_table': 'API_News',
            },
            bases=('front.executor', models.Model),
        ),
        migrations.CreateModel(
            name='API_Promotions',
            fields=[
                ('executor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='front.executor')),
                ('link', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка')),
                ('title', models.CharField(blank=True, max_length=250, null=True, verbose_name='Заголовок акций')),
                ('text', models.CharField(blank=True, max_length=100, null=True, verbose_name='Текст акций')),
                ('createdat', models.DateTimeField(auto_now=True, db_column='createdAt')),
                ('updatedat', models.DateTimeField(auto_now_add=True, db_column='updatedAt')),
            ],
            options={
                'verbose_name': 'Скидка',
                'verbose_name_plural': 'Скидки',
                'db_table': 'API_Promotions',
            },
            bases=('front.executor', models.Model),
        ),
        migrations.CreateModel(
            name='API_QaA',
            fields=[
                ('executor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='front.executor')),
                ('link', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка')),
                ('title', models.CharField(blank=True, max_length=250, null=True, verbose_name='Вопрос')),
                ('answer', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Ответ')),
                ('createdat', models.DateTimeField(auto_now=True, db_column='createdAt')),
                ('updatedat', models.DateTimeField(auto_now_add=True, db_column='updatedAt')),
            ],
            options={
                'verbose_name': 'Вопрос и ответ',
                'verbose_name_plural': 'Вопросы и ответы',
                'db_table': 'API_QaA',
            },
            bases=('front.executor', models.Model),
        ),
        migrations.CreateModel(
            name='API_TermsAnalyses',
            fields=[
                ('executor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='front.executor')),
                ('title', models.CharField(blank=True, max_length=15, null=True, verbose_name='Сроки анализов')),
                ('createdat', models.DateTimeField(auto_now=True, db_column='createdAt')),
                ('updatedat', models.DateTimeField(auto_now_add=True, db_column='updatedAt')),
            ],
            options={
                'verbose_name': 'Срок анализа',
                'verbose_name_plural': 'Сроки анализов',
                'db_table': 'API_TermsAnalyses',
            },
            bases=('front.executor',),
        ),
        migrations.CreateModel(
            name='API_Review',
            fields=[
                ('executor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='front.executor')),
                ('link', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка')),
                ('text_review', models.TextField(blank=True, null=True, verbose_name='Текст отзыва')),
                ('ratings', models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(5)], verbose_name='Рейтинг')),
                ('date', models.CharField(blank=True, max_length=255, null=True, verbose_name='Дата')),
                ('createdat', models.DateTimeField(auto_now=True, db_column='createdAt')),
                ('updatedat', models.DateTimeField(auto_now_add=True, db_column='updatedAt')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор отзыва')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'db_table': 'API_Reviews',
            },
            bases=('front.executor', models.Model),
        ),
        migrations.CreateModel(
            name='API_PackageAnalyses',
            fields=[
                ('executor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='front.executor')),
                ('name_of_package', models.CharField(max_length=250, verbose_name='Название пакетов анализов')),
                ('price_of_package', models.FloatField(verbose_name='Цена пакетов')),
                ('package', models.ManyToManyField(related_name='packages', to='front.api_analyses', verbose_name='Какие анализы входят')),
            ],
            options={
                'verbose_name': 'Пакет анализа',
                'verbose_name_plural': 'Пакеты анализов',
                'db_table': 'API_PackageAnalyses',
            },
            bases=('front.executor',),
        ),
        migrations.CreateModel(
            name='API_Image',
            fields=[
                ('executor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='front.executor')),
                ('link', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка')),
                ('banner_image', models.ImageField(upload_to='imgAnalyse', verbose_name='Картинка для баннера')),
                ('analyse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banner_images', to='front.api_analyses', verbose_name='Анализы')),
            ],
            options={
                'verbose_name': 'Картинка',
                'verbose_name_plural': 'Картинки',
                'db_table': 'API_Image',
            },
            bases=('front.executor', models.Model),
        ),
        migrations.AddField(
            model_name='api_analyses',
            name='biomaterial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='front.api_biomaterial', verbose_name='Биоматериал'),
        ),
        migrations.AddField(
            model_name='api_analyses',
            name='category',
            field=models.ForeignKey(db_column='category', null=True, on_delete=django.db.models.deletion.CASCADE, to='front.api_categoryanalyses', verbose_name='Категорий анализов'),
        ),
        migrations.AddField(
            model_name='api_analyses',
            name='terms_of_analyzes',
            field=models.ForeignKey(db_column='terms_of_analyzes', null=True, on_delete=django.db.models.deletion.CASCADE, to='front.api_termsanalyses', verbose_name='Сроки анализов'),
        ),
    ]
