# Generated by Django 4.1.2 on 2022-10-11 09:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authenticate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='API_AboutUs',
            fields=[
                ('title', models.CharField(blank=True, max_length=250, primary_key=True, serialize=False, verbose_name='Заголовок')),
                ('text', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Текст')),
                ('image', models.ImageField(blank=True, null=True, upload_to='imgAboutUs', verbose_name='Картинка')),
                ('createdat', models.DateTimeField(auto_now=True, db_column='createdAt')),
                ('updatedat', models.DateTimeField(auto_now_add=True, db_column='updatedAt')),
                ('link', models.CharField(max_length=250, verbose_name='Ссылка для О нас')),
            ],
            options={
                'verbose_name': 'О нас',
                'verbose_name_plural': 'О нас',
                'db_table': 'API_AboutUs',
            },
        ),
        migrations.CreateModel(
            name='API_Biomaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, null=True, verbose_name='Биоматериалы')),
                ('createdat', models.DateTimeField(auto_now=True, db_column='createdAt')),
                ('updatedat', models.DateTimeField(auto_now_add=True, db_column='updatedAt')),
            ],
            options={
                'verbose_name': 'Биоматериал',
                'verbose_name_plural': 'Биоматериалы',
                'db_table': 'API_Biomaterial',
            },
        ),
        migrations.CreateModel(
            name='API_CategoryAnalyses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('createdat', models.DateTimeField(auto_now=True, db_column='createdAt')),
                ('updatedat', models.DateTimeField(auto_now_add=True, db_column='updatedAt')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'db_table': 'API_CategoryAnalyses',
            },
        ),
        migrations.CreateModel(
            name='API_Contacts',
            fields=[
                ('address', models.CharField(blank=True, max_length=100, primary_key=True, serialize=False, verbose_name='Адрес')),
                ('phone_number', models.CharField(blank=True, max_length=11, null=True, verbose_name='Номер телефона')),
                ('map', models.CharField(blank=True, max_length=250, null=True, verbose_name='Карта')),
                ('createdat', models.DateTimeField(auto_now=True, db_column='createdAt')),
                ('updatedat', models.DateTimeField(auto_now_add=True, db_column='updatedAt')),
                ('link', models.CharField(max_length=250, verbose_name='Ссылка для контактов')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
                'db_table': 'API_Contacts',
            },
        ),
        migrations.CreateModel(
            name='API_News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_news', models.FileField(blank=True, max_length=255, null=True, upload_to='imgNews', verbose_name='Картинка новости')),
                ('title', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Заголовок новости')),
                ('href', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка')),
                ('date', models.CharField(blank=True, max_length=255, null=True, verbose_name='Дата')),
                ('createdat', models.DateTimeField(auto_now=True, db_column='createdAt')),
                ('updatedat', models.DateTimeField(auto_now_add=True, db_column='updatedAt')),
                ('link', models.CharField(max_length=250, null=True, verbose_name='Cсылка для новости (Пример: Заголовок новости-)')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'db_table': 'API_News',
            },
        ),
        migrations.CreateModel(
            name='API_Promotions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, null=True, verbose_name='Заголовок акций')),
                ('text', models.CharField(blank=True, max_length=100, null=True)),
                ('createdat', models.DateTimeField(auto_now=True, db_column='createdAt')),
                ('updatedat', models.DateTimeField(auto_now_add=True, db_column='updatedAt')),
                ('link', models.CharField(max_length=250, verbose_name='Ссылка для скидок')),
            ],
            options={
                'verbose_name': 'Скидка',
                'verbose_name_plural': 'Скидки',
                'db_table': 'API_Promotions',
            },
        ),
        migrations.CreateModel(
            name='API_QaA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('answer', models.CharField(blank=True, max_length=1000, null=True)),
                ('createdat', models.DateTimeField(auto_now=True, db_column='createdAt')),
                ('updatedat', models.DateTimeField(auto_now_add=True, db_column='updatedAt')),
                ('link', models.CharField(max_length=250, verbose_name='Ссылка для вопросов и ответов')),
            ],
            options={
                'verbose_name': 'Вопрос и ответ',
                'verbose_name_plural': 'Вопросы и ответы',
                'db_table': 'API_QaA',
            },
        ),
        migrations.CreateModel(
            name='API_TermsAnalyses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=15, null=True, verbose_name='Сроки анализов')),
                ('createdat', models.DateTimeField(auto_now=True, db_column='createdAt')),
                ('updatedat', models.DateTimeField(auto_now_add=True, db_column='updatedAt')),
            ],
            options={
                'verbose_name': 'Срок анализа',
                'verbose_name_plural': 'Сроки анализов',
                'db_table': 'API_TermsAnalyses',
            },
        ),
        migrations.CreateModel(
            name='API_Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_review', models.TextField(blank=True, null=True)),
                ('ratings', models.IntegerField(validators=[django.core.validators.MaxValueValidator(5)], verbose_name='Рейтинг')),
                ('date', models.CharField(blank=True, max_length=255, null=True, verbose_name='Дата')),
                ('createdat', models.DateTimeField(auto_now=True, db_column='createdAt')),
                ('updatedat', models.DateTimeField(auto_now_add=True, db_column='updatedAt')),
                ('link', models.CharField(max_length=250, verbose_name='Ссылка для отзывов')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='authenticate.api_users', verbose_name='Автор отзыва')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'db_table': 'API_Reviews',
            },
        ),
        migrations.CreateModel(
            name='Api_Analyses',
            fields=[
                ('title', models.CharField(blank=True, max_length=1000, verbose_name='Короткий заголовок')),
                ('long_title', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Длинный заголовк')),
                ('is_unique', models.BooleanField(blank=True, verbose_name='Уникальный')),
                ('research_id', models.CharField(blank=True, max_length=250, primary_key=True, serialize=False, verbose_name='Код анализа')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='Цена')),
                ('preparation_doctor', models.TextField(blank=True, null=True, verbose_name='Инструкция для врача ')),
                ('banner_img', models.ImageField(blank=True, max_length=1000, null=True, upload_to='imgAnalyse', verbose_name='Картинка для баннера')),
                ('document_img', models.ImageField(blank=True, max_length=1000, null=True, upload_to='imgAnalyse', verbose_name='Картинка для документа')),
                ('main_img', models.ImageField(blank=True, max_length=1000, null=True, upload_to='imgAnalyse', verbose_name='Главная картинка')),
                ('description_patient', models.TextField(blank=True, null=True, verbose_name='Описание для пациентов')),
                ('preparation_patient', models.TextField(blank=True, null=True, verbose_name='Инструкция для пациентов')),
                ('description_doctor', models.TextField(blank=True, null=True, verbose_name='Описание для врачей')),
                ('createdat', models.DateTimeField(auto_now=True, db_column='createdAt')),
                ('updatedat', models.DateTimeField(auto_now_add=True, db_column='updatedAt')),
                ('vendor_code', models.CharField(max_length=250, verbose_name='Артикул анализа')),
                ('link', models.CharField(max_length=250, null=True, verbose_name='Cсылка для новости (Пример: Короткий заголовок-Код анализа)')),
                ('biomaterial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='front.api_biomaterial', verbose_name='Биоматериал')),
                ('category', models.ForeignKey(db_column='category', on_delete=django.db.models.deletion.CASCADE, to='front.api_categoryanalyses', verbose_name='Категорий анализов')),
                ('terms_of_analyzes', models.ForeignKey(db_column='terms_of_analyzes', on_delete=django.db.models.deletion.CASCADE, to='front.api_termsanalyses', verbose_name='Сроки анализов')),
            ],
            options={
                'verbose_name': 'Анализ',
                'verbose_name_plural': 'Анализы',
                'db_table': 'API_Analyses',
            },
        ),
    ]
