# Generated by Django 4.1.2 on 2022-10-12 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api_analyses',
            name='biomaterial',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='front.api_biomaterial', verbose_name='Биоматериал'),
            preserve_default=False,
        ),
    ]
