# Generated by Django 4.1.2 on 2022-10-11 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api_analyses',
            name='link',
            field=models.CharField(max_length=250, null=True, verbose_name='Cсылка для анализа (Пример: Короткий заголовок-Код анализа (на латинице))'),
        ),
        migrations.AlterField(
            model_name='api_news',
            name='img_news',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='imgNews', verbose_name='Картинка новости'),
        ),
    ]
