# Generated by Django 4.1.2 on 2022-10-09 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='api_analyses',
            name='id',
        ),
        migrations.AlterField(
            model_name='api_analyses',
            name='research_id',
            field=models.CharField(blank=True, max_length=100, primary_key=True, serialize=False, verbose_name='Код анализа'),
        ),
    ]
