# Generated by Django 4.1.2 on 2022-10-25 05:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0002_remove_api_image_link_remove_api_review_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='api_packageanalyses',
            name='createdat',
            field=models.DateTimeField(auto_now=True, db_column='createdAt'),
        ),
        migrations.AddField(
            model_name='api_packageanalyses',
            name='link',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка'),
        ),
        migrations.AddField(
            model_name='api_packageanalyses',
            name='main_img',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to='imgAnalyse', verbose_name='Главная картинка'),
        ),
        migrations.AddField(
            model_name='api_packageanalyses',
            name='terms_of_analyzes',
            field=models.ForeignKey(db_column='terms_of_analyzes', null=True, on_delete=django.db.models.deletion.CASCADE, to='front.api_termsanalyses', verbose_name='Сроки анализов'),
        ),
        migrations.AddField(
            model_name='api_packageanalyses',
            name='updatedat',
            field=models.DateTimeField(auto_now_add=True, db_column='updatedAt', default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='api_promotions',
            name='image',
            field=models.ImageField(default=1, upload_to='imgPromotion', verbose_name='Картинка для акций'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='api_promotions',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст акций'),
        ),
        migrations.AlterField(
            model_name='api_review',
            name='name',
            field=models.CharField(max_length=30, null=True, verbose_name='Имя'),
        ),
    ]
