# Generated by Django 4.1.2 on 2022-10-31 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0003_api_packageanalyses_createdat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='api_categoryanalyses',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_category', to='front.api_categoryanalyses', verbose_name='Название категорий'),
        ),
        migrations.AlterField(
            model_name='api_categoryanalyses',
            name='title',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Название подкатегорий'),
        ),
    ]
