# Generated by Django 4.1.2 on 2022-10-11 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0003_remove_api_analyses_banner_img_api_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api_image',
            name='analyse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banner_img', to='front.api_analyses'),
        ),
    ]
