# Generated by Django 4.1.2 on 2022-11-03 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0004_api_categoryanalyses_parent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='API_Partners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='imgPartners', verbose_name='Картинка')),
                ('url', models.URLField(max_length=250, verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Партнер',
                'verbose_name_plural': 'Партнеры',
                'db_table': 'API_Partners',
            },
        ),
        migrations.AlterField(
            model_name='api_categoryanalyses',
            name='title',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Название'),
        ),
    ]
