# Generated by Django 4.1.2 on 2022-11-18 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0005_api_partners_alter_api_categoryanalyses_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='api_categoryanalyses',
            options={'ordering': ['-createdat'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.RemoveField(
            model_name='api_news',
            name='href',
        ),
    ]
