# Generated by Django 4.1.2 on 2022-11-18 05:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0006_alter_api_categoryanalyses_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='api_aboutus',
            options={'ordering': ['-createdat'], 'verbose_name': 'О нас', 'verbose_name_plural': 'О нас'},
        ),
        migrations.AlterModelOptions(
            name='api_analyses',
            options={'ordering': ['-createdat'], 'verbose_name': 'Анализ', 'verbose_name_plural': 'Анализы'},
        ),
        migrations.AlterModelOptions(
            name='api_biomaterial',
            options={'ordering': ['-createdat'], 'verbose_name': 'Биоматериал', 'verbose_name_plural': 'Биоматериалы'},
        ),
        migrations.AlterModelOptions(
            name='api_contacts',
            options={'ordering': (['-createdat'],), 'verbose_name': 'Контакт', 'verbose_name_plural': 'Контакты'},
        ),
        migrations.AlterModelOptions(
            name='api_image',
            options={'ordering': ['-createdat'], 'verbose_name': 'Картинка', 'verbose_name_plural': 'Картинки'},
        ),
        migrations.AlterModelOptions(
            name='api_news',
            options={'ordering': ['-createdat'], 'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AlterModelOptions(
            name='api_packageanalyses',
            options={'ordering': ['-createdat'], 'verbose_name': 'Пакет анализа', 'verbose_name_plural': 'Пакеты анализов'},
        ),
        migrations.AlterModelOptions(
            name='api_promotions',
            options={'ordering': ['-createdat'], 'verbose_name': 'Скидка', 'verbose_name_plural': 'Скидки'},
        ),
        migrations.AlterModelOptions(
            name='api_review',
            options={'ordering': ['-createdat'], 'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.AlterModelOptions(
            name='api_termsanalyses',
            options={'ordering': ['-createdat'], 'verbose_name': 'Срок анализа', 'verbose_name_plural': 'Сроки анализов'},
        ),
        migrations.AddField(
            model_name='api_image',
            name='createdat',
            field=models.DateTimeField(auto_now=True, db_column='createdAt'),
        ),
        migrations.AddField(
            model_name='api_image',
            name='updatedat',
            field=models.DateTimeField(auto_now_add=True, db_column='updatedAt', default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='api_partners',
            name='createdat',
            field=models.DateTimeField(auto_now=True, db_column='createdAt'),
        ),
        migrations.AddField(
            model_name='api_partners',
            name='updatedat',
            field=models.DateTimeField(auto_now_add=True, db_column='updatedAt', default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
