# Generated by Django 4.1.2 on 2022-11-18 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0008_alter_api_partners_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='api_news',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст новости'),
        ),
        migrations.AlterField(
            model_name='api_news',
            name='title',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Заголовок новости'),
        ),
    ]
