# Generated by Django 4.1.2 on 2022-11-18 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0009_api_news_text_alter_api_news_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='api_packageanalyses',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Описание пакетов анализов'),
        ),
    ]
