# Generated by Django 4.1.2 on 2022-11-18 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0010_api_packageanalyses_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api_packageanalyses',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание пакетов анализов'),
        ),
    ]
