# Generated by Django 4.1.2 on 2022-11-22 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0011_alter_api_packageanalyses_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api_packageanalyses',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name=''),
        ),
    ]
