# Generated by Django 4.1.2 on 2022-10-19 07:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='API_Appointment',
            fields=[
                ('title_appointment', models.CharField(blank=True, max_length=100, primary_key=True, serialize=False, verbose_name='Заголовок записи')),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('createdat', models.DateTimeField(auto_now=True, db_column='createdAt')),
                ('updatedat', models.DateTimeField(auto_now_add=True, db_column='updatedAt')),
                ('belongs_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Записи',
                'db_table': 'Api_Appointment',
            },
        ),
    ]
