# Generated by Django 4.1.2 on 2022-10-11 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='API_Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255, verbose_name='Электронная почта')),
                ('password', models.CharField(blank=True, max_length=255, null=True, verbose_name='Пароль')),
                ('password2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Повторите пароль')),
                ('phone_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер телефона')),
                ('avatar', models.ImageField(blank=True, max_length=255, null=True, upload_to='', verbose_name='Картинка пользователя')),
                ('createdat', models.DateTimeField(auto_now=True, db_column='createdAt')),
                ('updatedat', models.DateTimeField(auto_now_add=True, db_column='updatedAt')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес')),
                ('username', models.CharField(max_length=20, unique=True, verbose_name='Имя пользователя')),
                ('firstname', models.CharField(blank=True, max_length=20, null=True, verbose_name='Имя')),
                ('lastname', models.CharField(blank=True, max_length=20, null=True, verbose_name='Фамилия')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'db_table': 'API_Users',
            },
        ),
    ]
