# Generated by Django 4.1.2 on 2022-11-07 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='api_users',
            name='password2',
        ),
        migrations.AlterField(
            model_name='api_users',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
