# Generated by Django 4.1.2 on 2022-10-12 09:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api_users',
            name='email',
            field=models.EmailField(max_length=255, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='api_users',
            name='phone_number',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Введен неправильный номер телефноа', regex='[+]*\\d{11}')], verbose_name='Номер телефона'),
        ),
    ]
