# Generated by Django 4.1.2 on 2022-10-12 09:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0002_alter_api_users_email_alter_api_users_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api_users',
            name='phone_number',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Введен неправильный номер телефноа', regex='^\\+?77(\\d{9})$')], verbose_name='Номер телефона'),
        ),
    ]
